repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v5.0.0
      hooks:
          - id: check-merge-conflict
          - id: check-yaml
          - id: trailing-whitespace
          - id: check-symlinks
          - id: end-of-file-fixer
          - id: mixed-line-ending
          - id: trailing-whitespace
    - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
      rev: "3.0.3"
      hooks:
          - id: editorconfig-checker
            alias: ec
            exclude: '(pnpm-lock\.yaml|\.lock|LICENSE|\.gitmodules|\.bru|sandbox/localnet/crates/indexer/)$'
    - repo: local
      hooks:
          - id: prettier
            name: prettier
            entry: prettier --write --ignore-unknown
            language: system
            types: [text]
