/**
 * Integration tests for the deploy-all pipeline.
 *
 * Runs against a real Sui localnet via Docker. Tests are sequential —
 * each phase depends on the previous one. Deployment runs once (~5 min)
 * and all assertions share state via describe-level variables.
 *
 * A fresh Ed25519 keypair is generated inside the sui-localnet container
 * via `sui keytool generate`, then extracted and imported into the host's
 * `sui` CLI keystore. No manual PRIVATE_KEY is needed.
 *
 * Prerequisites:
 *   - Docker running
 *   - `sui` CLI on PATH
 *   - Git submodule initialized (external/deepbook/)
 *
 * Usage:
 *   cd sandbox
 *   pnpm test:integration
 */

import { describe, test, expect, beforeAll, afterAll } from "vitest";
import { spawnSync } from "child_process";
import fs from "fs/promises";
import path from "path";
import { fileURLToPath } from "url";

import { SuiClient } from "@mysten/sui/client";
import { Ed25519Keypair } from "@mysten/sui/keypairs/ed25519";
import type { Keypair } from "@mysten/sui/cryptography";

import {
    startLocalnet,
    configureAndStartLocalnetServices,
    startOracleService,
    startMarketMaker,
} from "../utils/docker-compose";
import { MoveDeployer, type DeploymentResult } from "../utils/deployer";
import { ensureMinimumBalance, getDeploymentEnv } from "../utils/helpers";
import { updateEnvFile } from "../utils/env";
import { readContainerKey, importKeyToHostCli, defaultSuiToolsImage } from "../utils/keygen";
import { setupPythOracles, type PythOracleIds } from "../utils/oracle";
import { PoolCreator, type PoolInfo } from "../utils/pool";
import { expectValidSuiId, waitForUrl, expectContainerRunning } from "./helpers/assertions";

// ---------------------------------------------------------------------------
// Resolve paths — avoid importing config.ts (has dotenv/config side effect)
// ---------------------------------------------------------------------------

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const SANDBOX_ROOT = path.resolve(__dirname, "../..");
const ENV_PATH = path.join(SANDBOX_ROOT, ".env");
const DEPLOYMENTS_DIR = path.join(SANDBOX_ROOT, "deployments");

const RPC_URL = "http://127.0.0.1:9000";
const FAUCET_HOST = "http://127.0.0.1:9123";

// ---------------------------------------------------------------------------
// Docker cleanup helper
// ---------------------------------------------------------------------------

function dockerDown(cwd: string): void {
    spawnSync("docker", ["compose", "--profile", "localnet", "down", "-v", "--remove-orphans"], {
        cwd,
        encoding: "utf-8",
        stdio: "inherit",
    });
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

describe("deploy-all pipeline (localnet)", () => {
    // Shared mutable state — populated by successive tests
    let client: SuiClient;
    let signer: Keypair;
    let signerAddress: string;
    let deployedPackages: Map<string, DeploymentResult>;
    let pythOracleIds: PythOracleIds;
    let pool: PoolInfo;
    let manifestPath: string;

    // Exit handler ref so we can deregister in afterAll
    let exitHandler: (() => void) | undefined;

    beforeAll(async () => {
        client = new SuiClient({ url: RPC_URL });

        // ── Write minimal .env for Docker Compose ────────────────────
        // PRIVATE_KEY is a placeholder — docker-compose validates all
        // ${VAR:?...} refs even for services we don't start yet.
        // The real key is generated inside the container in the first test.
        const placeholderKey = Ed25519Keypair.generate().getSecretKey();
        const envContent =
            [
                `PRIVATE_KEY=${placeholderKey}`,
                `NETWORK=localnet`,
                `SUI_TOOLS_IMAGE=${process.env.SUI_TOOLS_IMAGE ?? defaultSuiToolsImage()}`,
                `FORCE_REGENESIS=true`,
            ].join("\n") + "\n";
        await fs.writeFile(ENV_PATH, envContent, "utf-8");

        // ── Clean slate: tear down any leftover containers ───────────
        dockerDown(SANDBOX_ROOT);

        // ── Register exit handler to clean up on crash/Ctrl+C ────────
        exitHandler = () => dockerDown(SANDBOX_ROOT);
        process.on("exit", exitHandler);
    }, 300_000);

    // ----------------------------------------------------------------
    // Phase 1: Start localnet + read the key generated by the container
    // ----------------------------------------------------------------
    test("starts localnet", async () => {
        const { rpcPort, faucetPort } = await startLocalnet(SANDBOX_ROOT);
        expect(rpcPort).toBe(9000);
        expect(faucetPort).toBe(9123);

        // RPC should be responding
        await waitForUrl(RPC_URL, { timeoutMs: 30_000, label: "RPC" });

        // Faucet should be responding
        await waitForUrl(FAUCET_HOST, { timeoutMs: 30_000, label: "Faucet" });

        // Containers should be running
        expectContainerRunning("sui-localnet");
        expectContainerRunning("deepbook-postgres");

        // Read the keypair that sui-localnet generated at startup
        const { keypair, privateKey } = readContainerKey(SANDBOX_ROOT);
        signer = keypair;
        signerAddress = keypair.getPublicKey().toSuiAddress();

        // Replace the placeholder in .env with the real key
        updateEnvFile(SANDBOX_ROOT, { PRIVATE_KEY: privateKey });

        // Import into the host's sui CLI for `sui client publish`
        importKeyToHostCli(privateKey, signerAddress);
    }, 600_000);

    // ----------------------------------------------------------------
    // Phase 2: Fund deployer
    // ----------------------------------------------------------------
    test("funds deployer", async () => {
        await ensureMinimumBalance(client, signerAddress, FAUCET_HOST);

        const { totalBalance } = await client.getBalance({ owner: signerAddress });
        expect(BigInt(totalBalance)).toBeGreaterThanOrEqual(BigInt(1_000_000_000));
    }, 60_000);

    // ----------------------------------------------------------------
    // Phase 3: Deploy Move packages
    // ----------------------------------------------------------------
    test("deploys Move packages", async () => {
        const deployer = new MoveDeployer(client, signer, "localnet");
        deployedPackages = await deployer.deployAll();

        // Should deploy all 5 packages
        expect(deployedPackages.size).toBe(5);
        expect([...deployedPackages.keys()].sort()).toEqual([
            "deepbook",
            "deepbook_margin",
            "margin_liquidation",
            "pyth",
            "token",
        ]);

        // All packageIds should be valid Sui IDs
        for (const [, result] of deployedPackages) {
            expectValidSuiId(result.packageId);
        }

        // Token should have ProtectedTreasury
        const token = deployedPackages.get("token")!;
        const treasury = token.createdObjects.find((o) =>
            o.objectType.includes("ProtectedTreasury"),
        );
        expect(treasury).toBeDefined();

        // DeepBook should have Registry and AdminCap
        const deepbook = deployedPackages.get("deepbook")!;
        const registry = deepbook.createdObjects.find((o) => o.objectType.includes("Registry"));
        const adminCap = deepbook.createdObjects.find((o) =>
            o.objectType.includes("DeepbookAdminCap"),
        );
        expect(registry).toBeDefined();
        expect(adminCap).toBeDefined();
    }, 480_000);

    // ----------------------------------------------------------------
    // Phase 4: Write package IDs to .env
    // ----------------------------------------------------------------
    test("writes package IDs to .env", async () => {
        const envUpdates = getDeploymentEnv(deployedPackages, {});
        envUpdates.FIRST_CHECKPOINT = "0";
        updateEnvFile(SANDBOX_ROOT, envUpdates);

        const envContent = await fs.readFile(ENV_PATH, "utf-8");
        expect(envContent).toContain("DEEPBOOK_PACKAGE_ID=");
        expect(envContent).toContain("DEEP_TOKEN_PACKAGE_ID=");
        expect(envContent).toContain("DEEP_TREASURY_ID=");
        expect(envContent).toContain("FIRST_CHECKPOINT=0");
    }, 10_000);

    // ----------------------------------------------------------------
    // Phase 5: Start localnet services (indexer, server, faucet, MM)
    // ----------------------------------------------------------------
    test("starts localnet services", async () => {
        const deepbookPkg = deployedPackages.get("deepbook")!;
        const marginPkg = deployedPackages.get("deepbook_margin");
        await configureAndStartLocalnetServices(
            {
                corePackageId: deepbookPkg.packageId,
                ...(marginPkg && { marginPackageId: marginPkg.packageId }),
            },
            SANDBOX_ROOT,
        );

        // Indexer metrics should respond
        await waitForUrl("http://127.0.0.1:9184/metrics", {
            timeoutMs: 180_000,
            label: "Indexer metrics",
        });

        // DeepBook server should respond
        await waitForUrl("http://127.0.0.1:9008/", {
            timeoutMs: 120_000,
            label: "DeepBook server",
        });

        // Faucet service should respond
        await waitForUrl("http://127.0.0.1:9009/", {
            timeoutMs: 60_000,
            label: "DeepBook faucet",
        });
    }, 600_000);

    // ----------------------------------------------------------------
    // Phase 6: Setup Pyth oracles
    // ----------------------------------------------------------------
    test("creates Pyth oracles", async () => {
        pythOracleIds = await setupPythOracles(client, signer, deployedPackages);

        expectValidSuiId(pythOracleIds.deepPriceInfoObjectId);
        expectValidSuiId(pythOracleIds.suiPriceInfoObjectId);

        // The two IDs should be distinct
        expect(pythOracleIds.deepPriceInfoObjectId).not.toBe(pythOracleIds.suiPriceInfoObjectId);

        // Objects should exist on-chain
        const deepObj = await client.getObject({ id: pythOracleIds.deepPriceInfoObjectId });
        expect(deepObj.data).toBeDefined();

        const suiObj = await client.getObject({ id: pythOracleIds.suiPriceInfoObjectId });
        expect(suiObj.data).toBeDefined();
    }, 60_000);

    // ----------------------------------------------------------------
    // Phase 7: Create DEEP/SUI pool
    // (Must run before the oracle service starts, because the oracle
    //  transacts with the same signer every 10 s — racing for gas coins
    //  causes equivocation errors.)
    // ----------------------------------------------------------------
    test("creates DEEP/SUI pool", async () => {
        const poolCreator = new PoolCreator(client, signer, FAUCET_HOST);
        pool = await poolCreator.createPool(deployedPackages);

        expectValidSuiId(pool.poolId);

        // Wait for the transaction to be indexed before querying
        await client.waitForTransaction({ digest: pool.transactionDigest });

        // Pool object should exist on-chain with correct type
        const poolObj = await client.getObject({
            id: pool.poolId,
            options: { showType: true },
        });
        expect(poolObj.data).toBeDefined();
        expect(poolObj.data!.type).toContain("::pool::Pool<");
    }, 60_000);

    // ----------------------------------------------------------------
    // Phase 8: Write oracle env + start oracle service
    // ----------------------------------------------------------------
    test("starts oracle service", async () => {
        const pythPkg = deployedPackages.get("pyth")!;
        updateEnvFile(SANDBOX_ROOT, {
            PYTH_PACKAGE_ID: pythPkg.packageId,
            DEEP_PRICE_INFO_OBJECT_ID: pythOracleIds.deepPriceInfoObjectId,
            SUI_PRICE_INFO_OBJECT_ID: pythOracleIds.suiPriceInfoObjectId,
        });

        const envContent = await fs.readFile(ENV_PATH, "utf-8");
        expect(envContent).toContain("PYTH_PACKAGE_ID=");
        expect(envContent).toContain("DEEP_PRICE_INFO_OBJECT_ID=");
        expect(envContent).toContain("SUI_PRICE_INFO_OBJECT_ID=");

        await startOracleService(SANDBOX_ROOT);

        // Oracle status endpoint should respond
        await waitForUrl("http://127.0.0.1:9010/", {
            timeoutMs: 120_000,
            label: "Oracle service",
        });
    }, 120_000);

    // ----------------------------------------------------------------
    // Phase 9: Write deployment manifest
    // ----------------------------------------------------------------
    test("writes deployment manifest", async () => {
        const config = {
            network: {
                type: "localnet",
                rpcUrl: RPC_URL,
                faucetUrl: FAUCET_HOST,
            },
            packages: Object.fromEntries(
                Array.from(deployedPackages.entries()).map(([name, data]) => [
                    name,
                    {
                        packageId: data.packageId,
                        objects: data.createdObjects.map((obj) => ({
                            objectId: obj.objectId,
                            objectType: obj.objectType,
                        })),
                        transactionDigest: data.transactionDigest,
                    },
                ]),
            ),
            pythOracles: {
                deepPriceInfoObjectId: pythOracleIds.deepPriceInfoObjectId,
                suiPriceInfoObjectId: pythOracleIds.suiPriceInfoObjectId,
            },
            pool: {
                poolId: pool.poolId,
                baseCoin: `${deployedPackages.get("token")!.packageId}::deep::DEEP`,
                quoteCoin: "0x2::sui::SUI",
                transactionDigest: pool.transactionDigest,
            },
            deploymentTime: new Date().toISOString(),
            deployerAddress: signerAddress,
        };

        await fs.mkdir(DEPLOYMENTS_DIR, { recursive: true });

        const now = new Date();
        const date = now.toISOString().slice(0, 10);
        const time = now.toISOString().slice(11, 19).replace(/:/g, "-");
        manifestPath = path.join(DEPLOYMENTS_DIR, `${date}_${time}_localnet.json`);
        await fs.writeFile(manifestPath, JSON.stringify(config, null, 2));

        // File should exist and be valid JSON
        const raw = await fs.readFile(manifestPath, "utf-8");
        const parsed = JSON.parse(raw);

        expect(parsed.network.type).toBe("localnet");
        expect(parsed.packages).toBeDefined();
        expect(parsed.packages.token.packageId).toBeTruthy();
        expect(parsed.packages.deepbook.packageId).toBeTruthy();
        expect(parsed.pool.poolId).toBeTruthy();
        expect(parsed.pythOracles.deepPriceInfoObjectId).toBeTruthy();
        expect(parsed.pythOracles.suiPriceInfoObjectId).toBeTruthy();
        expect(parsed.deployerAddress).toBe(signerAddress);
    }, 10_000);

    // ----------------------------------------------------------------
    // Phase 10: Start market maker
    // ----------------------------------------------------------------
    test("starts market maker", async () => {
        updateEnvFile(SANDBOX_ROOT, {
            DEEPBOOK_PACKAGE_ID: deployedPackages.get("deepbook")!.packageId,
            POOL_ID: pool.poolId,
            BASE_COIN_TYPE: `${deployedPackages.get("token")!.packageId}::deep::DEEP`,
            DEPLOYER_ADDRESS: signerAddress,
        });

        await startMarketMaker(SANDBOX_ROOT);

        // Health endpoint should eventually respond
        await waitForUrl("http://127.0.0.1:3001/health", {
            timeoutMs: 60_000,
            label: "Market maker",
        });
    }, 120_000);

    // ----------------------------------------------------------------
    // E2E: Faucet distributes SUI
    // ----------------------------------------------------------------
    test("faucet distributes SUI", async () => {
        // Generate a fresh keypair to receive funds
        const freshKeypair = Ed25519Keypair.generate();
        const freshAddress = freshKeypair.getPublicKey().toSuiAddress();

        const res = await fetch("http://127.0.0.1:9009/faucet", {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({ address: freshAddress, token: "SUI" }),
        });
        expect(res.status).toBe(200);

        // Wait for tx to settle
        await new Promise((r) => setTimeout(r, 3_000));

        const { totalBalance } = await client.getBalance({ owner: freshAddress });
        expect(BigInt(totalBalance)).toBeGreaterThan(0n);
    }, 30_000);

    // ----------------------------------------------------------------
    // E2E: Oracle reports prices
    // ----------------------------------------------------------------
    test("oracle reports prices", async () => {
        // Give the oracle time to perform at least one update cycle
        await new Promise((r) => setTimeout(r, 15_000));

        const res = await fetch("http://127.0.0.1:9010/");
        expect(res.status).toBe(200);

        const body = await res.json();
        expect(body).toBeDefined();
        // The oracle status endpoint returns JSON with status and update info
        expect(body.status).toBeDefined();
    }, 60_000);

    // ----------------------------------------------------------------
    // Cleanup
    // ----------------------------------------------------------------
    afterAll(async () => {
        // Tear down containers
        dockerDown(SANDBOX_ROOT);

        // Remove test .env and shared keystore
        for (const f of [ENV_PATH, path.join(DEPLOYMENTS_DIR, ".sui-keystore")]) {
            try {
                await fs.unlink(f);
            } catch {
                // may not exist
            }
        }

        // Remove test deployment manifests
        if (manifestPath) {
            try {
                await fs.unlink(manifestPath);
            } catch {
                // may not exist
            }
        }

        // Deregister exit handler
        if (exitHandler) {
            process.removeListener("exit", exitHandler);
            exitHandler = undefined;
        }
    }, 120_000);
});
