import { readFileSync, writeFileSync } from "fs";
import path from "path";
import { z } from "zod";
import { getEnvFileName } from "./docker-compose";
import log from "./logger";

/** Keys that must be present with non-empty values after cleaning. */
export const REQUIRED_ENV_KEYS = ["PRIVATE_KEY", "SUI_TOOLS_IMAGE"] as const;

/**
 * Keys the user sets manually — everything else is auto-generated by
 * deploy-all and gets cleaned up. This allowlist approach means adding
 * new auto-generated env vars requires zero changes in down.ts.
 */
export const USER_ENV_KEYS = new Set([
    "PRIVATE_KEY",
    "RPC_URL",
    "SUI_TOOLS_IMAGE",
    "FORCE_REGENESIS",
    "RUST_LOG",
    "DATABASE_URL",
    "MM_FALLBACK_MID_PRICE",
    "MM_SPREAD_BPS",
    "MM_LEVELS_PER_SIDE",
    "MM_LEVEL_SPACING_BPS",
    "MM_ORDER_SIZE_BASE",
    "MM_REBALANCE_INTERVAL_MS",
    "MM_HEALTH_CHECK_PORT",
    "MM_METRICS_PORT",
]);

export interface EnvValidationResult {
    valid: boolean;
    fileExists: boolean;
    present: string[];
    missing: string[];
}

/**
 * Read-only validation of the .env file against REQUIRED_ENV_KEYS.
 * Returns a structured result — does NOT throw or log.
 */
export function validateEnvFile(sandboxRoot: string): EnvValidationResult {
    const envPath = path.join(sandboxRoot, ".env");
    let content: string;
    try {
        content = readFileSync(envPath, "utf-8");
    } catch {
        return {
            valid: false,
            fileExists: false,
            present: [],
            missing: [...REQUIRED_ENV_KEYS],
        };
    }

    const parsed: Record<string, string> = {};
    for (const line of content.split(/\r?\n/)) {
        const match = line.match(/^([A-Za-z_][A-Za-z0-9_]*)\s*=(.*)/);
        if (match) parsed[match[1]] = match[2];
    }

    const present: string[] = [];
    const missing: string[] = [];
    for (const key of REQUIRED_ENV_KEYS) {
        if (parsed[key] !== undefined && parsed[key].trim() !== "") {
            present.push(key);
        } else {
            missing.push(key);
        }
    }

    return { valid: missing.length === 0, fileExists: true, present, missing };
}

/**
 * Remove all key=value lines from .env EXCEPT those whose key is in
 * `preserveKeys`. Comments and blank lines are always kept.
 * No-op if the file doesn't exist.
 *
 * After filtering, validates that required keys exist with non-empty values
 * and warns (without throwing) on any violations.
 */
export function cleanEnvFile(sandboxRoot: string, preserveKeys: Set<string>): void {
    const envPath = path.join(sandboxRoot, ".env");
    let content: string;
    try {
        content = readFileSync(envPath, "utf-8");
    } catch {
        log.warn("No .env file found, skipping key cleanup");
        return;
    }

    const lines = content.split(/\r?\n/);
    const result = lines.filter((line) => {
        const match = line.match(/^([A-Za-z_][A-Za-z0-9_]*)\s*=/);
        if (!match) return true; // keep comments and blank lines
        return preserveKeys.has(match[1]);
    });

    // Validate preserved keys: required keys must exist with non-empty values,
    // and any other preserved key should not have an empty value.
    const preserved: Record<string, string> = {};
    for (const line of result) {
        const match = line.match(/^([A-Za-z_][A-Za-z0-9_]*)\s*=(.*)/);
        if (match) preserved[match[1]] = match[2];
    }

    const requiredShape = Object.fromEntries(REQUIRED_ENV_KEYS.map((k) => [k, z.string().min(1)]));
    const schema = z
        .object(requiredShape)
        .passthrough()
        .pipe(z.record(z.string(), z.string().min(1)));
    const validation = schema.safeParse(preserved);
    if (!validation.success) {
        const problems = validation.error.issues.map((i) => i.path.join("."));
        log.warn(`Env validation issues after clean: ${problems.join(", ")}`);
    }

    writeFileSync(envPath, result.join("\n"), "utf-8");
}

/**
 * Update or set key=value pairs in the env file.
 * Preserves existing keys not in updates, preserves order and comments.
 * Uses SANDBOX_ENV_FILE when set (tests use ".env.test"), otherwise ".env".
 */
export function updateEnvFile(sandboxRoot: string, updates: Record<string, string>): void {
    const envPath = path.join(sandboxRoot, getEnvFileName());
    let content = "";
    try {
        content = readFileSync(envPath, "utf-8");
    } catch {
        // .env may not exist yet
    }

    const keys = new Set(Object.keys(updates));
    const lines = content.split(/\r?\n/);
    const updated = new Set<string>();
    let result: string[] = [];

    for (const line of lines) {
        const match = line.match(/^([A-Za-z_][A-Za-z0-9_]*)\s*=/);
        if (match && keys.has(match[1])) {
            result.push(`${match[1]}=${updates[match[1]]}`);
            updated.add(match[1]);
        } else {
            result.push(line);
        }
    }

    for (const key of keys) {
        if (!updated.has(key)) {
            result.push(`${key}=${updates[key]}`);
        }
    }

    writeFileSync(envPath, result.join("\n") + (result.length ? "\n" : ""), "utf-8");
}
