import { execFileSync, spawnSync } from "child_process";
import { readFileSync, existsSync } from "fs";
import path from "path";
import { Ed25519Keypair } from "@mysten/sui/keypairs/ed25519";
import { LOCALNET_RPC_PORT } from "./docker-compose";

/**
 * Read the keypair that the sui-localnet container generated at startup.
 *
 * The container's command runs `sui keytool generate ed25519` and copies
 * the keystore to `deployments/.sui-keystore` (bind-mounted shared volume).
 * The last entry in the keystore is the generated key.
 */
export function readContainerKey(sandboxRoot: string): {
    keypair: Ed25519Keypair;
    privateKey: string;
} {
    const keystorePath = path.join(sandboxRoot, "deployments", ".sui-keystore");

    // Poll until the file appears (the container writes it shortly after start)
    const deadline = Date.now() + 30_000;
    while (!existsSync(keystorePath)) {
        if (Date.now() > deadline) {
            throw new Error(`Timed out waiting for ${keystorePath}. Is sui-localnet running?`);
        }
        spawnSync("sleep", ["1"]);
    }

    // Each keystore entry is base64(scheme_byte + secret_key_bytes).
    // The last entry is the key generated by the container's startup command.
    const keystore: string[] = JSON.parse(readFileSync(keystorePath, "utf-8"));
    const lastKeyBase64 = keystore[keystore.length - 1];
    const secretKey = Buffer.from(lastKeyBase64, "base64").slice(1);

    const keypair = Ed25519Keypair.fromSecretKey(secretKey);
    return {
        keypair,
        privateKey: keypair.getSecretKey(), // bech32 suiprivkey1...
    };
}

/**
 * Import a bech32 private key into the host's `sui` CLI keystore and
 * configure a `localnet` environment pointing at the local RPC.
 */
export function importKeyToHostCli(privateKey: string, address: string): void {
    // Import key (idempotent — warns if already present)
    execFileSync("sui", ["keytool", "import", privateKey, "ed25519"], {
        encoding: "utf-8",
        stdio: "pipe",
    });

    // Ensure the localnet environment exists (ignore error if alias taken)
    spawnSync(
        "sui",
        [
            "client",
            "new-env",
            "--alias",
            "localnet",
            "--rpc",
            `http://127.0.0.1:${LOCALNET_RPC_PORT}`,
        ],
        { encoding: "utf-8", stdio: "pipe" },
    );

    // Switch to localnet env, then set the active address
    execFileSync("sui", ["client", "switch", "--env", "localnet"], {
        encoding: "utf-8",
        stdio: "pipe",
    });
    execFileSync("sui", ["client", "switch", "--address", address], {
        encoding: "utf-8",
        stdio: "pipe",
    });
}

/**
 * Auto-detect the SUI_TOOLS_IMAGE based on CPU architecture.
 */
export function defaultSuiToolsImage(): string {
    return process.arch === "arm64" ? "mysten/sui-tools:compat-arm64" : "mysten/sui-tools:compat";
}
